services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: vapi
      POSTGRES_USER: vapi
      PGUSER: vapi
      PGPASSWORD: vapi
      POSTGRES_PASSWORD: vapi
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vapi -d vapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  modelq:
    build:
      context: .
      dockerfile: modelq.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: "postgresql://vapi:vapi@postgres:5432/vapi"
      ADMIN_KEY: "impel_intelligence_best_intelligence"
    ports:
      - "8000:8000" # Change as needed for your app
    command: ["--netuid", "231", "--subtensor.network", "test"]


  workerq:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: "postgresql://vapi:vapi@postgres:5432/vapi"
    ports:
      - "8001:8000" # Change as needed for your app




volumes:
  postgres_data:
