services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: vapi
      POSTGRES_USER: vapi
      PGUSER: vapi
      PGPASSWORD: vapi
      POSTGRES_PASSWORD: vapi
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vapi -d vapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
