services:
  validator_service:
    image: ghcr.io/impel-intelligence/validator_script_image:latest
    environment:
      TZ: 'UTC'
      ORG_NAME: ${ORG_NAME}
    volumes:
      - ~/.bittensor/wallets/:/root/.bittensor/wallets/
    command: ${VALIDATOR_COMMAND}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224" # Use localhost to reference the host's Fluentd
        tag: "validator_service_${ORG_NAME}"
    depends_on:
      - fluentd # Ensures Fluentd starts before this service

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ORG_NAME: ${ORG_NAME}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "900" # Checks for updates every 5 minutes
    command: --debug
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224" # Use localhost to reference the host's Fluentd
        tag: "watchtower_${ORG_NAME}"
    depends_on:
      - fluentd # Ensures Fluentd starts before this service

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluent
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf # Mount your Fluentd config
    environment:
      FLUENTD_ARGS: "--no-supervisor -q"
      LOG_KEY: ${LOG_KEY} # Pass the LOG_KEY to Fluentd
