services:
  validator_service:
    image: ghcr.io/impel-intelligence/validator_script_image:latest
    environment:
      TZ: 'UTC'
    volumes:
      - ~/.bittensor/wallets/:/root/.bittensor/wallets/
    command: python validator.py --wallet.name coldkey4 --wallet.hotkey hotkey4 --netuid 58 --subtensor.network finney --wallet.path "/root/.bittensor/wallets/" --offline --immediate --debug
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224" # Use localhost to reference the host's Fluentd
        tag: "validator_service"
    depends_on:
      - fluentd # Ensures Fluentd starts before this service

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "900" # Checks for updates every 5 minutes
    command: --debug
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224" # Use localhost to reference the host's Fluentd
        tag: "watchtower"
    depends_on:
      - fluentd # Ensures Fluentd starts before this service

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluent
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf # Mount your Fluentd config
    environment:
      FLUENTD_ARGS: "--no-supervisor -q"
