name: Push Official NGINX Image to GCP Artifact Registry

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  push-nginx:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional, not strictly needed here)
      - name: Checkout code
        uses: actions/checkout@v3

      # Check authorized user
      - name: Check Triggering User
        run: |
          AUTHORIZED_USERS=("pravin-X109" "ManavShahWasTaken" "donaldknoller")
          if [[ ! " ${AUTHORIZED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
            echo "::error::Unauthorized user: ${{ github.actor }}"
            exit 1
          fi

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for GCP Artifact Registry
      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      # Pull the official NGINX image
      - name: Pull NGINX image
        run: docker pull nginx:alpine

      # Tag the NGINX image for GCP Artifact Registry
      - name: Tag NGINX image
        run: |
          docker tag nginx:alpine us-east1-docker.pkg.dev/impel-dippy-dev/dippy-backend-artifact-repository/sn58-validation-api-v2:latest

      # Push the tagged image to GCP Artifact Registry
      - name: Push NGINX image
        run: |
          docker push us-east1-docker.pkg.dev/impel-dippy-dev/dippy-backend-artifact-repository/sn58-validation-api-v2:latest