name: Docker Build and Push Validator Script
on:
  push:
    branches:
    - main # Trigger the workflow on pushes to the 'main' branch
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu image as the runner environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3 # Action to fetch the latest code from the repository

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3 # Updated to the latest version of Docker login action
      with:
        registry: ghcr.io # Specify the GitHub Container Registry (GHCR) as the target
        username: ${{ github.actor }} # Use the GitHub Actions-provided actor username
        password: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub Actions-provided token for authentication

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -f validator_updater/Dockerfile.validator \ # Specify the Dockerfile location
          -t ghcr.io/impel-intelligence/validator_script_image:latest .

    # Step 4: Push the Docker image
    - name: Push Docker image
      run: |
        docker push ghcr.io/impel-intelligence/validator_script_image:latest # Push the built image with the 'latest' tag
        docker push ghcr.io/impel-intelligence/validator_script_image:$(date +%Y%m%d%H%M%S) # Push the built image with a timestamp tag for versioning
