name: Basic Workflow

on:
  workflow_dispatch: {} # Allow manual triggering of the workflow

jobs:
  placeholder-job:
    runs-on: ubuntu-latest # Use the latest Ubuntu image as the runner environment

    steps:
    - name: Placeholder step
      run: echo "This is a basic workflow with manual triggering enabled."
