name: Validation API SN58
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (required for building the Docker image)
      - name: Checkout code
        uses: actions/checkout@v3

      # Check authorized user
      - name: Check Triggering User
        run: |
          AUTHORIZED_USERS=("pravin-X109" "ManavShahWasTaken" "donaldknoller")
          if [[ ! " ${AUTHORIZED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
            echo "::error::Unauthorized user: ${{ github.actor }}"
            exit 1
          fi

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for GCP Artifact Registry
      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      # Build the custom Python Docker image using vapi.Dockerfile
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --build-arg SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --build-arg ADMIN_KEY=${{ secrets.ADMIN_KEY }} \
            --build-arg HF_ACCESS_TOKEN=${{ secrets.HF_ACCESS_TOKEN }} \
            --build-arg HF_USER=${{ secrets.HF_USER }} \
            --build-arg DIPPY_KEY=${{ secrets.DIPPY_KEY }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg DATASET_API_KEY=${{ secrets.DATASET_API_KEY }} \
            --build-arg POSTGRES_URL=${{ secrets.POSTGRES_URL }} \
            --build-arg 58_VALIDATION_API=${{ secrets.VALIDATION_API_58 }} \
            -t us-east1-docker.pkg.dev/bittensor-449517/bittensor-artifacts/sn58-validation-api-v2:latest \
            -f vapi_actions.Dockerfile .

      # Push the custom Python Docker image to GCP Artifact Registry
      - name: Push Docker Image
        run: |
          docker push us-east1-docker.pkg.dev/bittensor-449517/bittensor-artifacts/sn58-validation-api-v2:latest